FROM python:3.8-alpine

ENV PORT=8080

ENV CONFIG_FILE_LOCATION=/app/config.toml

RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*

RUN mkdir /app

WORKDIR /app

ADD scripts/entrypoint.sh /app

COPY requirements.txt .

RUN pip --no-cache-dir install -r requirements.txt

COPY . .

RUN pip --no-cache-dir install .

CMD ["./entrypoint.sh"]
